server: 
  port: 7003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka
#hmily:
#  server:
#    configMode: local
#    appName: account1
#  #  如果server.configMode eq local 的时候才会读取到这里的配置信息.
#  config:
#    appName: account1
#    serializer: kryo
#    contextTransmittalMode: threadLocal
#    scheduledThreadMax: 16
#    scheduledRecoveryDelay: 60
#    scheduledCleanDelay: 60
#    scheduledPhyDeletedDelay: 600
#    scheduledInitDelay: 30
#    recoverDelayTime: 60
#    cleanDelayTime: 180
#    limit: 200
#    retryMax: 10
#    bufferSize: 8192
#    consumerThreads: 16
#    asyncRepository: true
#    autoSql: true
#    phyDeleted: true
#    storeDays: 3
#    repository: mysql
#repository:
#  database:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hmily?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    maxActive: 20
#    minIdle: 10
#    connectionTimeout: 30000
    idleTimeout: 600000
